/// Flutter icons MetroidIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MetroidIcons
///      fonts:
///       - asset: fonts/MetroidIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MetroidIcons {
  MetroidIcons._();

  static const _kFontFam = 'MetroidIcons';
  static const String? _kFontPkg = null;

  static const IconData target_seo_and_web_svgrepo_com = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bomb_weapon_svgrepo_com = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData samus_helmet_svgrepo_com = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
